# Numpy Assignment 

# Assignment 1 

Q1. 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1. 

In [2]:
import numpy as np 
array = np.random.randint(1,21, size = (5,5)) 
print("Ooriginal Array") 
print(array) 

# All the elemts to be replaced with 1 
array[:, 2] = 1 
print("Modified Array") 
print(array) 

Ooriginal Array
[[20 15 13 20  4]
 [19 18 11 12 14]
 [20 14 11  8 12]
 [ 1 10 14  7  4]
 [ 3 18 20  3  6]]
Modified Array
[[20 15  1 20  4]
 [19 18  1 12 14]
 [20 14  1  8 12]
 [ 1 10  1  7  4]
 [ 3 18  1  3  6]]


Q2. . Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0. 

In [3]:
array = np.arange(1,17).reshape((4,4)) 
print("Original Array") 
print(array) 

# Modified Array '
np.fill_diagonal(array, 0) 
print("Modified Array") 
print(array) 

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


# Assignment 2  

Q1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
# Te code for the following question is as: 
import numpy as np 
array = np.arange(1,37).reshape((6,6)) 
print("Original Array") 
print(array) 

sub_array = array[2:5, 1:4] 
print("Sub Array") 
print(sub_array)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array
[[14 15 16]
 [20 21 22]
 [26 27 28]]


Q2.  Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
# The code for the above question is as: 
array = np.random.randint(1,21, size = (5,5)) 
print("Original Array") 
print(array)  

# Extracting all the alements as: 
border_elements = np.concatenate((array[0,:], array[-1, :], array[1:-1, 0], array[1:-1, -1])) 
print("Border Elements") 
print(border_elements)  

'''
Here, in this code we come to see that the first arrat is about the 0th row and include all the columns. 
The second array has the last row with all the columns included. 
The third array has all the rows except the first and the last one including all the first column. 
The last array has all the rows except the first and the last one and the last column. 
''' 


Original Array
[[ 5  2 16  7 19]
 [10  2  3 14 12]
 [ 6 17  1  5 13]
 [ 5  4 16  4  8]
 [17 18  9  4 17]]
Border Elements
[ 5  2 16  7 19 17 18  9  4 17 10  6  5 12 13  8]


'\nHere, in this code we come to see that the first arrat is about the 0th row and include all the columns. \nThe second array has the last row with all the columns included. \nThe third array has all the rows except the first and the last one including all the first column. \nThe last array has all the rows except the first and the last one and the last column. \n'

# Assignment 3 

Q1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division. 

In [6]:
# The coode for all the elements is given as: 
array1   = np.random.randint(1,11, size = (3,4)) 
array2 = np.random.randint(1,11, size  =(3,4)) 
print ("Array 1") 
print(array1) 

print("Array 2") 
print(array2)  

# Element wise addition, subtraction, multiplication and division 
addition = array1 + array2 
subtraction = array1 - array2 
multiplication = array1 * array2 
division = array1 / array2 

print("Element wise addition") 
print(addition) 

print("Element wise subtraction") 
print(subtraction) 

print("Element wise Multiplication") 
print(multiplication)

print("Element wise Division") 
print(division) 

Array 1
[[ 7  9  5 10]
 [ 5  1  1 10]
 [ 5  2  8  7]]
Array 2
[[4 5 3 9]
 [1 5 4 2]
 [2 2 5 7]]
Element wise addition
[[11 14  8 19]
 [ 6  6  5 12]
 [ 7  4 13 14]]
Element wise subtraction
[[ 3  4  2  1]
 [ 4 -4 -3  8]
 [ 3  0  3  0]]
Element wise Multiplication
[[28 45 15 90]
 [ 5  5  4 20]
 [10  4 40 49]]
Element wise Division
[[1.75       1.8        1.66666667 1.11111111]
 [5.         0.2        0.25       5.        ]
 [2.5        1.         1.6        1.        ]]


Q2. . Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
# The code for the following question is as: 
array = np.arange(1,17).reshape((4,4)) 
print("Original Array") 
print(array) 

row_sum = np.sum(array, axis = 1) 
column_sum = np.sum(array, axis = 0) 

print("Row wise Sum") 
print(row_sum) 

print("Column wise Sum") 
print(column_sum) 

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise Sum
[10 26 42 58]
Column wise Sum
[28 32 36 40]


# Assignment 4 

Q1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array. 

In [8]:
#  The code for the above questin is as: 
array = np.random.randint(1,21,size = (5,5)) 
print("Original Array") 
print(array) 

# The statistical values are calculated as: 
mean = np.mean(array) 
median = np.median(array) 
std_dev = np.std(array) 
var = np.var(array) 

print("Mean", mean) 
print("Median", median) 
print("Standard Deviation", std_dev) 
print("Variance: ", var) 

Original Array
[[10 11 18  6 13]
 [ 5  6 10 14 15]
 [10 14  2  6  4]
 [16 11 18 20 12]
 [10 11 12 12 15]]
Mean 11.24
Median 11.0
Standard Deviation 4.4924826098717405
Variance:  20.1824


Q2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1). 

In [9]:
# The code for the abbove question is as: 
import numpy as np 
array = np.arange(1,10).reshape((3,3)) 
print("Original Array") 
print(array) 

# Normalizing the array can be doenn as:  
mean = np.mean(array) 
std_dev = np.std(array) 

normalized_array = (array - mean)/ std_dev 

print("Normalized Array") 
print(normalized_array) 

Original Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


# Assignment 5 

Q1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting. 

In [10]:
# The code for the above question is as: 
array = np.random.randint(1,11, size = (3,3)) 
row_array = np.random.randint(1,11, size = (3,)) 

print("Original Array") 
print(array) 

print("Row_Array") 
print(row_array) 

result = array + row_array 
print("Resulting Array") 
print(array) 

Original Array
[[ 8  8  6]
 [ 8  2  6]
 [10  2  4]]
Row_Array
[5 5 6]
Resulting Array
[[ 8  8  6]
 [ 8  2  6]
 [10  2  4]]


Q2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting. 

In [11]:
# The code for the above question is as: 
array = np.random.randint(1,11, size = (4,4)) 
column_array = np.random.randint(1,11, size = (4,)) 
print("Original Array") 
print(array) 
print("1 D Array") 
print(column_array)  

result = array - column_array.reshape(4,1) 
print("Resulting Array") 
print(result) 

Original Array
[[ 2  6  3  9]
 [ 5  5  1  5]
 [ 4  8  6  2]
 [ 4 10  8  7]]
1 D Array
[1 2 7 9]
Resulting Array
[[ 1  5  2  8]
 [ 3  3 -1  3]
 [-3  1 -1 -5]
 [-5  1 -1 -2]]


# Assignment 6 

Q1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues. 

In [12]:
import numpy as np 
matrix = np.random.randint(1,11, size = (3,3)) 
print("Original Matrix") 
print(matrix) 

# Computing the determinant 
determinant = np.linalg.det(matrix) 
print("Determinant value: ", determinant) 

# Computing the inverse 
inverse = np.linalg.inv(matrix) 
print("Inverse: ") 
print(inverse) 

# Eigen values can be calculated as: 
eigenvalues = np.linalg.eigvals(matrix) 
print("Eigen values: ", eigenvalues)

Original Matrix
[[10  5  4]
 [ 5  8  3]
 [ 4  9  6]]
Determinant value:  172.0000000000001
Inverse: 
[[ 0.12209302  0.03488372 -0.09883721]
 [-0.10465116  0.25581395 -0.05813953]
 [ 0.0755814  -0.40697674  0.31976744]]
Eigen values:  [17.80188736+0.j          3.09905632+0.24030563j  3.09905632-0.24030563j]


Q2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays. 

In [13]:
# The code for the above question is as: 
array1 = np.random.randint(1,11, size = (2,3)) 
array2 = np.random.randint(1,11, size =(3,2)) 

print("Array 1: ")
print(array1) 

print("Array 2: ") 
print(array2) 

# Performing the matrix multiplication as: 
result  = np.dot(array1, array2) 
print("Matrix Multiplication result: ") 
print(result)

Array 1: 
[[10  5  2]
 [ 3 10  2]]
Array 2: 
[[7 8]
 [7 5]
 [8 5]]
Matrix Multiplication result: 
[[121 115]
 [107  84]]


# Assignment 7 

Q1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
# The code for the above question is as: 
array = np.arange(1,10).reshape((3,3)) 
print("Original Array") 
print(array) 

reshaped_array = array.reshape((1,9)) 
print(reshaped_array) 

reshaped_array_2 = array.reshape((9,1)) 
print(reshaped_array_2) 

Original Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Q2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5). 

In [15]:
# The code for the above question is as: 
array = np.random.randint(1,21, size = (5,5)) 
print("Original Array") 
print(array)  

# Flattening the array 
flattended_array = array.flatten() 
print("Flattended Array:") 
print(flattended_array) 

# Reshaping the array back to 5,5 
reshaped_array = flattended_array.reshape((5,5)) 
print(reshaped_array) 

Original Array
[[ 1 12  5 15 17]
 [ 4  1  5  9  5]
 [ 4  9 20  4  3]
 [15 20  6  8  3]
 [ 5  3  8  6 15]]
Flattended Array:
[ 1 12  5 15 17  4  1  5  9  5  4  9 20  4  3 15 20  6  8  3  5  3  8  6
 15]
[[ 1 12  5 15 17]
 [ 4  1  5  9  5]
 [ 4  9 20  4  3]
 [15 20  6  8  3]
 [ 5  3  8  6 15]]


# Assignment 8 

Q1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array. 

In [16]:
# The code for the above question is as: 
array = np.random.randint(1,21, size = (5,5)) 
print("Original Array") 
print(array)  

corners = array[[0,0,-1,-1], [0,-1,0,-1]] 
print("Corner Elements") 
print(corners) 

Original Array
[[ 4 16  3 11 13]
 [20 15 15  7 20]
 [ 9 12  4 15  8]
 [ 9  6  3 14 17]
 [16 20 18  8  3]]
Corner Elements
[ 4 13 16  3]


Q2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [17]:
# The code for the above question is as: 
array = np.random.randint(1,21, size = (4,4)) 
print(array) 

array[array > 10] = 10 
print("Modified Array") 
print(array) 

[[ 7  7 17 16]
 [ 4 18 12 15]
 [20 15  6 18]
 [14 16 18  3]]
Modified Array
[[ 7  7 10 10]
 [ 4 10 10 10]
 [10 10  6 10]
 [10 10 10  3]]


# Assignment 9 

Q1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age. 

In [18]:
# The code for the above question is as: 
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')] 
data = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype = data_type) 

print("Original Array") 
print(data) 

# Sorting the array 
sorted_data = np.sort(data, order = 'age') 
print(sorted_data) 

Original Array
[('Alice', 25, 55. ) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
[('Charlie', 20, 65.2) ('Alice', 25, 55. ) ('Bob', 30, 85.3)]


Q2.  Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [19]:
# The code for the abve uestion is as: 
data_type = [('x', 'i4'), ('y', 'i4')] 
data = np.array([(1,2), (3,4), (5,6)], dtype = data_type) 

print(data) 

distances = np.sqrt((data['x'][:, np.newaxis]- data['x'])**2 + (data['y'][:, np.newaxis]- data['y'])**2) 
print("Euclidean Distances")
print(distances) 

[(1, 2) (3, 4) (5, 6)]
Euclidean Distances
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


# Assignment 10 

Q1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements. 

In [20]:
# The code fr the question is as: 
import numpy.ma as ma 

array = np.random.randint(1,21, size = (4,4)) 
masked_array = ma.masked_array(array, 10) 
print(masked_array) 

sum_masked = masked_array.sum() 
print("Sum of masked elements: ", sum_masked) 

[[-- -- -- --]
 [-- -- -- --]
 [-- -- -- --]
 [-- -- -- --]]
Sum of masked elements:  --


Q2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements. 

In [21]:
# The cde for  the question is as: 
array = np.random.randint(1,21, size = (3,3)) 
masked_array = ma.masked_array(array, mask = np.eye(3, dtype = bool)) 

print("Original Array") 
print(array) 

print(masked_array) 

mean_unmasked = masked_array.mean() 
masked_array = masked_array.filled(mean_unmasked) 
print("Modified masked array") 
print(masked_array) 

Original Array
[[ 7  1  9]
 [14  4 12]
 [ 5  2 16]]
[[-- 1 9]
 [14 -- 12]
 [5 2 --]]
Modified masked array
[[ 7  1  9]
 [14  7 12]
 [ 5  2  7]]
