# Numpy  
Numpy is a fundamental library for scientific computing in Python. It provides the support foor arrays and the matrices along with the collection of mathematical functions to operate on these data structures. 

In [1]:
# importing the numpy library and carrying out the functions on it 
import numpy as np 
arr1 = np.array([1,2,3,4,5]) 
print(arr1) 
print(type(arr1)) 
print(arr1.shape) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
# printing in the list formmat 
for num in arr1: 
    print(num) 

1
2
3
4
5


In [5]:
arr2 = np.array([1,2,3,4,5]) 
print(arr2.shape)  

arr2.reshape(1,5) 

(5,)


array([[1, 2, 3, 4, 5]])

Here, in the abve code we have reshaped the array to the shape (1,5) and then the array has been made.   
In single dimensional array, we have single brackets but in the multi dimensional array, we have the 2 brackets opening and closing. 

In [ ]:
# Creating it directly as: 
# 1D array 
arr2 = np.array([[1,2,3,4,5]]) 
print(arr2) 

[[1 2 3 4 5]]


In [8]:
# Printing the multi dimensional array as: 
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]]) 
print(arr2) 
print(arr2.shape) 
print(arr2.ndim) 

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
2


In the above code, we are able to print the multi dimensional array, shape and also the dimensionality. 

# Arange Function Codes and examples 

In [ ]:
np.arange(0,10,2) 
# Here, the array has been printed 

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10,2).reshape(5,1)  
# The reshaping of the array has been doone here 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
# printing the ones array code 
np.ones((3,4))  

# Here, the array has been printed in the shpae of 3x4 matrix with all the elements as 1 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Identity Matrix: An identity matrix is a matrix whixh consist of all the diagonal elements equal to 1 

In [ ]:
np.eye(3)  

# All diagonal elements are 1 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Attributes of Numpy array 

In [15]:
arr =  np.array([[1,2,3],[4,5,6]]) 

print("Array:\n", arr) 
print("Shape:", arr.shape) 
print("Number of dimensions:", arr.ndim) 
print("Size (number of elements): ", arr.size)
print("Data Type:", arr.dtype) 
print("Item size in bytes: ", arr.itemsize) 

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements):  6
Data Type: int64
Item size in bytes:  8


# Numpy Vectorized Operations 

In [16]:
arr1 = np.array([1,2,3,4,5]) 
arr2 = np.array([10,20,30,40,50]) 

#Element wise addition 
print("Addition: ", arr1 + arr2) 

# Element wise subtraction 
print("Subtraction: ", arr1 - arr2) 

# Element wise multiplication 
print("Multiplication:", arr1*arr2) 

# Element wise divison 
print("Division:", arr1/arr2) 

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [17]:
# Universal Function Examples 
arr = np.array([2,3,4,5,6]) 

# Square root 
print(np.sqrt(arr)) 

# Exponential 
print(np.exp(arr)) 

# Sin 
print(np.sin(arr)) 

# natural log 
print(np.log(arr)) 

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
# Array Slicing and Indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
print("Array:\n", arr)  

# The multi dimensiona; array gets printed 

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Note 
Indexing always starts from 0th index whether, it be row or column 

In [21]:
# Accessing the 0th row from the index as: 
arr[0] 

array([1, 2, 3, 4])

In [23]:
# Accessing the 0th elemnt from the 0th row 
print(arr[0][0])

1


In [ ]:
# From the matrix, accessing the 2nd and the thirs=d rows 
arr[1:]  

# Both rows are accessed 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Noww, among the above 2 rows obtained also, we want only the last 2 columns to be obtained 
arr[1:, 2:]  

array([[ 7,  8],
       [11, 12]])

In [27]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
# Suppose we ant the elements 3,4,7,8  
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [30]:
# Accessing 6,7,10,11 in the array  
print(arr[1:, 1:3]) 

[[ 6  7]
 [10 11]]


In [31]:
# Method fr modifying the array elements as: 
arr[0,0] = 100 
print(arr) 

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
# Printing the arrays as: 
arr[1:] = 100 
print(arr)  

# all the elements get printed as 100 

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


# Statistical Concepts: Normalization  
Normalization basically means to have a mean of 0 and standard  deviation of 1 

In [ ]:
# Example through code 
data = np.array([1,2,3,4,5]) 

# calculating the mean and standard deviation of the data 
mean = np.mean(data) 
std_dev = np.std(data) 

normalized_data = (data - mean)/ std_dev 
print("Normalized data:", normalized_data) 

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [34]:
# Some more examples of the numpy codes are as: 
data = np.array([1,2,3,4,5,6,7,8,9,10]) 

# mean 
mean = np.mean(data) 
print("Mean: ", mean) 

#Median 
median = np.median(data) 
print("Median: ", median) 

# Standard Deviation 
std_dev = np.std(data) 
print("Standard Deviation: ", std_dev) 

# Variance 
var = np.var(data) 
print("Variance: ", var) 

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [ ]:
# Logical Operation 
data = np.array([1,2,3,4,5,6,7,8,9,10]) 

data[(data >= 5) & (data <= 8)] 

# All the elements satisfying the condition get printed 

array([5, 6, 7, 8])